flags: {}
packages:
- '.'
- location:
    git: https://github.com/tobbebex/GPipe-Core.git
    commit: 4f7b9e3e909e1ec20fb18a5a22bc99429b920a86
  subdirs:
  - GPipe-Core
  extra-dep: true
extra-deps:
- GLFW-b-1.4.7.3
- bindings-GLFW-3.1.1.4
resolver: lts-3.1
