flags: {}
packages:
- '.'
- location: '../../@gpipe'
#   git: git@github.com:plredmond/GPipe-Core.git
#   commit: 
  subdirs: [ GPipe-Core ]
  extra-dep: true

extra-deps: []
resolver: nightly-2016-12-03
